on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: lab01/app_python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        working-directory: lab01/app_python
        run: |
          python -m pytest tests
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ruff
        working-directory: lab01/app_python
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        working-directory: lab01/app_python
        run: |
          docker build -t ilyasiluyanov/app_python:dev .
          docker push ilyasiluyanov/app_python:dev
