on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd lab01/app_python
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          cd lab01/app_python
          python -m pytest tests
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ruff
        run: |
          cd lab01/app_python
          python -m pip install --upgrade pip
          pip install ruff
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
          ruff --format=github --target-version=py310 .
